# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('eweb', '0003_remove_buyer_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.CharField(max_length=80, verbose_name=b'\xe6\x8f\x8f\xe8\xbf\xb0'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='brand',
            name='img_url',
            field=models.CharField(max_length=80, verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87url'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_display',
            field=models.BooleanField(default=True, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\x8f\xaf\xe8\xa7\x81'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=20, verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe5\x90\x8d\xe7\xa7\xb0'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='buyer',
            name='addr',
            field=models.CharField(max_length=80, verbose_name=b'\xe5\x9c\xb0\xe5\x9d\x80', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='buyer',
            name='city',
            field=models.CharField(max_length=20, verbose_name=b'\xe5\xb8\x82', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='buyer',
            name='province',
            field=models.CharField(max_length=20, verbose_name=b'\xe7\x9c\x81', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='buyer',
            name='real_name',
            field=models.CharField(max_length=20, verbose_name=b'\xe7\x9c\x9f\xe5\xae\x9e\xe5\xa7\x93\xe5\x90\x8d', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='buyer',
            name='register_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\xb3\xa8\xe5\x86\x8c\xe6\x97\xb6\xe9\x97\xb4'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='buyer',
            name='town',
            field=models.CharField(max_length=20, verbose_name=b'\xe5\x8e\xbf', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='buyer',
            name='user',
            field=models.OneToOneField(verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=20, verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe9\xa2\x9c\xe8\x89\xb2'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='color',
            name='parent_id',
            field=models.IntegerField(verbose_name=b'\xe9\xa2\x9c\xe8\x89\xb2\xe7\x88\xb6ID'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='img',
            name='is_def',
            field=models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe9\xbb\x98\xe8\xae\xa4'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='img',
            name='product_id',
            field=models.ForeignKey(verbose_name=b'\xe5\x95\x86\xe5\x93\x81ID', to='eweb.Product'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='img',
            name='url',
            field=models.ImageField(upload_to=b'productimages', verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87Url'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_id',
            field=models.ForeignKey(verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d', to='eweb.Buyer'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe7\x94\x9f\xe6\x88\x90\xe6\x97\xb6\xe9\x97\xb4'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver_fee',
            field=models.IntegerField(verbose_name=b'\xe8\xbf\x90\xe8\xb4\xb9'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.DateField(auto_now_add=True, verbose_name=b'\xe9\x80\x81\xe8\xb4\xa7\xe6\x97\xb6\xe9\x97\xb4'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='is_confirm',
            field=models.CharField(max_length=10, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe7\x94\xb5\xe8\xaf\x9d\xe7\xa1\xae\xe8\xae\xa4'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='is_pay',
            field=models.CharField(max_length=10, verbose_name=b'\xe6\x94\xaf\xe4\xbb\x98\xe7\x8a\xb6\xe6\x80\x81'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=100, verbose_name=b'\xe9\x99\x84\xe8\xa8\x80'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(serialize=False, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95ID', primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.FloatField(verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe9\x87\x91\xe9\xa2\x9d'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_state',
            field=models.CharField(max_length=10, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe7\x8a\xb6\xe6\x80\x81'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_cash',
            field=models.CharField(max_length=10, verbose_name=b'\xe8\xb4\xa7\xe5\x88\xb0\xe4\xbb\x98\xe6\xac\xbe\xe6\x96\xb9\xe5\xbc\x8f'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_way',
            field=models.CharField(max_length=10, verbose_name=b'\xe6\x94\xaf\xe4\xbb\x98\xe6\x96\xb9\xe5\xbc\x8f'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='total_fee',
            field=models.FloatField(verbose_name=b'\xe5\xba\x94\xe4\xbb\x98\xe9\x87\x91\xe9\xa2\x9d'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='amount',
            field=models.IntegerField(default=1, verbose_name=b'\xe8\xb4\xad\xe4\xb9\xb0\xe6\x95\xb0\xe9\x87\x8f'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='color',
            field=models.CharField(max_length=5, verbose_name=b'\xe9\xa2\x9c\xe8\x89\xb2\xe5\x90\x8d\xe7\xa7\xb0'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_id',
            field=models.ForeignKey(verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95ID', to='eweb.Order'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.FloatField(verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe9\x94\x80\xe5\x94\xae\xe4\xbb\xb7'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product_id',
            field=models.IntegerField(verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe7\xbc\x96\xe5\x8f\xb7'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product_name',
            field=models.CharField(max_length=80, verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe5\x90\x8d\xe7\xa7\xb0'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='size',
            field=models.CharField(max_length=5, verbose_name=b'\xe5\xb0\xba\xe7\xa0\x81'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_id',
            field=models.ForeignKey(verbose_name=b'\xe5\x93\x81\xe7\x89\x8cID', to='eweb.Brand'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(max_length=100, verbose_name=b'\xe9\xa2\x9c\xe8\x89\xb2\xe9\x9b\x86'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='product',
            name='create_time',
            field=models.DateTimeField(verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.ImageField(upload_to=b'productimages', verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe6\x8f\x8f\xe8\xbf\xb0'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.CharField(max_length=100, verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe5\xb1\x9e\xe6\x80\xa7\xe9\x9b\x86'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='product',
            name='is_commend',
            field=models.BooleanField(default=False, verbose_name=b'\xe6\x8e\xa8\xe8\x8d\x90'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='product',
            name='is_del',
            field=models.BooleanField(default=True, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\x88\xa0\xe9\x99\xa4'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='product',
            name='is_hot',
            field=models.BooleanField(default=True, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe7\x83\xad\xe9\x94\x80'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x96\xb0\xe5\x93\x81'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='product',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name=b'\xe4\xb8\x8a\xe4\xb8\x8b\xe6\x9e\xb6'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe5\x90\x8d\xe7\xa7\xb0'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='product',
            name='package_list',
            field=models.CharField(max_length=100, verbose_name=b'\xe5\x8c\x85\xe8\xa3\x85\xe6\xb8\x85\xe5\x8d\x95'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.IntegerField(serialize=False, verbose_name=b'ID\xe6\x88\x96\xe5\x95\x86\xe5\x93\x81\xe7\xbc\x96\xe5\x8f\xb7', primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(max_length=100, verbose_name=b'\xe5\xb0\xba\xe5\xaf\xb8\xe9\x9b\x86'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='product',
            name='type_id',
            field=models.ForeignKey(verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8bID', to='eweb.Producttype'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(verbose_name=b'\xe9\x87\x8d\xe9\x87\x8f\xef\xbc\x88\xe5\x85\x8b\xef\xbc\x89'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='is_del',
            field=models.BooleanField(default=True, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\xba\x9f\xe5\xbc\x83'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='name',
            field=models.CharField(max_length=20, verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe5\xb1\x9e\xe6\x80\xa7'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='producttype',
            name='is_display',
            field=models.BooleanField(default=True, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\x8f\xaf\xe8\xa7\x81'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=20, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='producttype',
            name='note',
            field=models.CharField(max_length=50, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='producttype',
            name='parent_id',
            field=models.IntegerField(verbose_name=b'\xe7\x88\xb6\xe5\x95\x86\xe5\x93\x81\xe7\xb1\xbb\xe5\x9e\x8bid'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sku',
            name='color_id',
            field=models.ForeignKey(verbose_name=b'\xe9\xa2\x9c\xe8\x89\xb2ID', to='eweb.Color'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sku',
            name='delive_fee',
            field=models.IntegerField(default=10, verbose_name=b'\xe8\xbf\x90\xe8\xb4\xb9'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sku',
            name='location',
            field=models.CharField(max_length=50, verbose_name=b'\xe4\xbb\x93\xe5\xba\x93\xe4\xbd\x8d\xe7\xbd\xae:\xe8\xb4\xa7\xe6\x9e\xb6\xe5\x8f\xb7'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sku',
            name='price',
            field=models.FloatField(verbose_name=b'\xe5\x94\xae\xe4\xbb\xb7'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sku',
            name='product_id',
            field=models.ForeignKey(verbose_name=b'\xe5\x95\x86\xe5\x93\x81ID', to='eweb.Product'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sku',
            name='sales',
            field=models.IntegerField(verbose_name=b'\xe9\x94\x80\xe9\x87\x8f'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sku',
            name='sizes',
            field=models.CharField(max_length=5, verbose_name=b'\xe5\xb0\xba\xe7\xa0\x81'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku_img',
            field=models.ImageField(upload_to=b'productimages', verbose_name=b'SKU\xe5\x9b\xbe\xe7\x89\x87'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sku',
            name='stock',
            field=models.IntegerField(verbose_name=b'\xe5\xba\x93\xe5\xad\x98'),
            preserve_default=True,
        ),
    ]
